### PR TITLE
Integrate fixes by ross-g

### PR DESCRIPTION
**Pull request by ross-g**
@cb109 Submitting this pull request with a couple of fixes that I have been using locally for a while now. I'm moving jobs today so have lots of code admin to tidy up!

### CODE REVIEW

**Comment by cb109** [comment]
@ross-g thanks Ross, this looks good. Nice job on making the commits do exactly one thing. I'll make sure to integrate and release soon, much appreciated! Have a good start at your new job :)

**Comment by cb109** [comment]
cb882d7 is in conflict with 746fb19cf88ddd988543: It's ultimately a matter of taste. I do prefer the current style, but will add a note to the docs on how to achieve your result.

**Comment by cb109** [comment]
Released as https://github.com/cb109/sublime3dsmax/releases/tag/0.11.0

Sibling PR to finally drop ST2 support: https://github.com/wbond/package_control_channel/pull/7416

@ross-g I cherry-picked your commits so your authorship to the changes is kept intact, but I did some additional changes and thus merged it in a separate PR, so I'll just close off this one later. 

You could do me a great favor and install version 0.11.0 from package control when you find the time and give me a quick feedback if things still work :) 

Thank you again for you repeated contribution :bow: :+1:

**Comment by ross-g** [comment]
Thanks @cb109 ! I've tested the release version from package control and it looks good on this end.

> [cb882d7](https://github.com/cb109/sublime3dsmax/commit/cb882d7ccaf394205eeaa7154e8bc78a70d645fa) is in conflict with [746fb19](https://github.com/cb109/sublime3dsmax/commit/746fb19cf88ddd988543de9c52eb38bfd55f0890): It's ultimately a matter of taste. I do prefer the current style, but will add a note to the docs on how to achieve your result.

I agree this principally comes down to taste, the larger motivation for fixing it was that the current behaviour is inconsistent with how other languages treat block commenting in Sublime. (ie block commenting at the indent level of the selection rather than enforcing block commenting at indent level 0) But I'm content keeping this as a local change.

Happy New Year! 👍

**Comment by cb109** [comment]
This should probably go to the package configuration at some point, relying on local edits is quite a horrible approach I admit :see_no_evil: 

Much appreciate the feedback! I hope you had a good start at your new place, happy new year @ross-g!

**Pull request merged**
